### ISSUE TITLE
Parentheses lacking when quotienting a product

### ISSUE THREAD

**Issue by GuillaumeGen** [ret/specifica#10]
Whenever printing the expression (I omit the position information, which are irrelevant here) `AS_Infix AS_DIV (AS_Infix AS_Mult (AS_Ident [] "x") (AS_Ident [] "y")) (AS_Ident [] "z")`, I get `x * y \div z` that TLA+ cannot parse because both multiplication and quotient have the same priority.
I would expect specifica to print `(x * y) \div z`.

**Comment by ret** [comment]
TLC doesn't accept (as you say):
  a * b \div c
and reports: "Precedence conflict between ops * ... and \div"
* and \div are at level 13, as specified on page 271 in the book.

Perhaps the right thing would be to error upon parsing the same way TLC does. But, for now, I will more liberally sprinkle parenthesis as you suggest. It'll break precise round-tripping, but I'm OK with that right now.

So, as you suggest, we'll print this expression as (a * b) \div c. Will take a little extra care to not do the same if the operators are the same, so we'll make sure to _not_ insert parens for e.g. a*b*c, as opposed to (a*b)*c.

**Comment by GuillaumeGen** [comment]
Thanks a lot for this fix.
