### ISSUE TITLE
Incorrect parsing of some indented expressions

### ISSUE THREAD

**Issue by Calvin-L** [ret/specifica#4]
Example:

```
$ cat test.txt
\/ /\ \E y \in {TRUE}: y
   /\ y
```
```
$ stack exec -- tle <test.txt 
** INPUT (pretty-printed):
\/ (/\ (\E y \in {TRUE}: y /\ y))

** RESULT:
TRUE
```

This example should actually fail because the final `y` is not underneath the quantifier. The expression should parse as `(\E y \in {TRUE}: y) /\ y`.

**Comment by ret** [comment]
Thank you for reporting, Calvin. Fixed in the parser.
