### ISSUE TITLE
Cross-product operator evaluation is incorrect

### ISSUE THREAD

**Issue by Calvin-L** [ret/specifica#8]
The README's example of cross product evaluation is incorrect.

```
$ stack exec -- tle <<<'LET S==1..3 IN S \X S'
** INPUT (pretty-printed):
LET S ==
      1..3
 IN S \X S

** RESULT:
<<{1,2,3},{1,2,3}>>
```

Correct output:
```
** RESULT:
{<<1,1>>,
 <<1,2>>,
 <<1,3>>,
 <<2,1>>,
 <<2,2>>,
 <<2,3>>,
 <<3,1>>,
 <<3,2>>,
 <<3,3>>}
```

This appears to be a bug in both tle's evaluation function and the documentation.

**Comment by ret** [comment]
Thank you for testing and reporting, Calvin! Really appreciate it.
